export const PRICING_PLAN = [
  {
    icon: "./bullseye-arrow.svg",
    title: "Essentiel",
    price: 179,
    currency: "USD",
    frequency: "/month",
    features: [
      "+2500 vues/mois",
      "+60 clics sur votre site",
      "+15 appels/mois",
      "+15 demandes d'itinéraires",
      "Plus de visibilité sur Google",
    ],
    cta: "Je m'abonne",
    description: "Réponse aux avis google inclus",
    mostPopular: false,
  },
  {
    icon: "./gem.svg",
    title: "Ultime",
    price: 439,
    currency: "USD",
    frequency: "/month",
    features: [
      "+6500 vues/mois",
      "+200 clics sur votre site",
      "+40 appels/mois",
      "+40 demandes d'itinéraires",
      "Plus de visibilité sur Google",
      "Réponse aux avis google inclus",
      "1 shooting",
      "QR code personnalisé",
    ],
    cta: "Je m'abonne",
    mostPopular: true,
  },
  {
    icon: "./bullseye-arrow.svg",
    title: "Premium",
    price: 319,
    currency: "USD",
    frequency: "/month",
    features: [
      "+11 000 vues/mois",
      "+500 clics sur votre site",
      "+80 appels/mois",
      "+80 demandes d'itinéraires",
      "Plus de visibilité sur Google",
      "Réponse aux avis google inclus",
      "1 shooting",
    ],
    cta: "Je m'abonne",
    mostPopular: false,
  },
];
